### PR TITLE
groups option in Kernel

### PR DESCRIPTION
**Pull request by mariogeiger**

### CODE REVIEW

**Comment by mariogeiger** [comment]
I still need to add tests

**Comment by mariogeiger** [comment]
I think with this you can make your `SmallConvolution` simpler.

**Comment by blondegeek** [comment]
Do you plan on also adding this group functionality to `e3nn.kernel_mod.Kernel`?

**Comment by mariogeiger** [comment]
Yes

**Comment by mariogeiger** [comment]
I have to add `groups` in `TensorProduct`. And at this point I think we come back to honorate your original request about `LearnableTensorProduct`

**Comment by mariogeiger** [comment]
Now I don't know if I want to implement `groups` everywhere or use the batch trick.

The barch trick imposes to have `Rs = groups * Rs_small`

**Comment by blondegeek** [comment]
See https://github.com/e3nn/e3nn/pull/117

**Pull request closed without merging**
