### PR TITLE
TensorSquare

### PR DESCRIPTION
**Pull request by mariogeiger**
At the end I needed to make a special implementation, it is not that trivial as we thought.

### CODE REVIEW

**Comment by bkmi** [comment]
Did you decide you wanted to work on this more?

**Comment by mariogeiger** [comment]
It is merged. I asked review to keep you updated on my changes

**Comment by bkmi** [comment]
But it was closed with unmerged commits?

**Comment by mariogeiger** [comment]
Yes but there is another merged PR that was built on top of this one with
extra uninteresting code

**Pull request closed without merging**
