### PR TITLE
explicitly specify device placement in random number generator in e3nn.math._normalize_activation.moment

### PR DESCRIPTION
**Pull request by lyuwen**
## Description
In line 17 of `e3nn/math/_normalize_activation.py`, I changed from 
https://github.com/e3nn/e3nn/blob/8c9891dbce85a2fd0ec25bc95f8d81c3c6619d3e/e3nn/math/_normalize_activation.py#L17
to
```python
    z = torch.randn(1_000_000, generator=gen, dtype=torch.float64, device="cpu").to(dtype=dtype, device=device)
```

## Motivation and Context
**Background**: I'm using E3NN in a training code written with pytorch-lightning. During the training process, I encountered the following error:
```python
  File "/opt/conda/lib/python3.10/site-packages/e3nn/nn/_fc.py", line 73, in __init__
    act = normalize2mom(act)
  File "/opt/conda/lib/python3.10/site-packages/e3nn/math/_normalize_activation.py", line 43, in __init__
    cst = moment(f, 2, dtype=torch.float64, device="cpu").pow(-0.5).item()
  File "/opt/conda/lib/python3.10/site-packages/e3nn/math/_normalize_activation.py", line 17, in moment
    z = torch.randn(1_000_000, generator=gen, dtype=torch.float64).to(dtype=dtype, device=device)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lightning/fabric/utilities/init.py", line 53, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
```
From the code I assume the process is to create a random number array on CPU and then copy to GPU. Under the environment of the pytorch-lightning, it must be trying the create the random number array on GPU and failed since everything else has been placed explicitly on CPU.
Therefore I propose to add the `device="cpu"` to the `torch.randn` function call, to avoid this error.

## How Has This Been Tested?
I have tested the fixed code training my own model. It successfully fixed the error.
Since the edit is minimal, it should be safe from introducing bugs.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/e3nn/e3nn/blob/main/.github/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [x] The modified code is cuda compatible (github tests don't test cuda) (if relevant).
- [ ] I have updated the [CHANGELOG](https://github.com/e3nn/e3nn/blob/main/.github/CHANGELOG.md).

### CODE REVIEW

**Comment by mitkotak** [comment]
Hey thanks for the PR. Looking at the function, I am seeing a `device` attribute in there. Did you try setting that to `cpu` ?

**Comment by mitkotak** [comment]
As I looking at your log more, looks like the issue is stemming from not taking in [a device in `FullyConnected`](https://github.com/e3nn/e3nn/blob/8c9891dbce85a2fd0ec25bc95f8d81c3c6619d3e/e3nn/nn/_fc.py#L51-L73) which is then propagated to `normalize2mom` and `moment`

**Comment by lyuwen** [comment]
True. Though the whole [normalize2mom](https://github.com/e3nn/e3nn/blob/8c9891dbce85a2fd0ec25bc95f8d81c3c6619d3e/e3nn/math/_normalize_activation.py#L9-L43) class seems hard-coded to put everything on cpu. Is that intended?

**Comment by mitkotak** [comment]
Yup thats weird. Can you please modify it to take in device from attribute, set default to CPU and then put in a pytest that checks this so that we are not breaking any backward compatibility ? Thanks !

**Comment by lyuwen** [comment]
Sure. I'll work on that.

**Comment by lyuwen** [comment]
So I changed the `"cpu"` to `device`. I noticed in commit c9655030aed505f3954deac1e59429d104c7baad, some [tests](https://github.com/e3nn/e3nn/blob/8c9891dbce85a2fd0ec25bc95f8d81c3c6619d3e/tests/math/normalize_activation_test.py) where added, and in this commit, the `dtype` and `device` where changed from the input `dtype` and `device` to `torch.float64` and `"cpu"` on purpose. Was there a reason behind this?

**Comment by mitkotak** [comment]
@mariogeiger

**Comment by mitkotak** [comment]
Thanks !

**Pull request merged**
