### PR TITLE
[WIP]: `o3.experimental.TensorSquarev2`

### PR DESCRIPTION
**Pull request by mitkotak**
- [ ] Need to sort out this ordering error for `0e + 1e`
```python
In [1]: expected
Out[1]: 
tensor([[ 1.3710,  1.3314, -0.4522, -3.3575,  0.8760, -0.1668,  0.6393,  2.6226,
         -1.2385,  0.1185]])

In [2]: current
Out[2]: 
tensor([[-0.4522, -3.3575,  0.8760,  1.3314,  1.3710, -0.1668,  0.6393,  2.6226,
         -1.2385,  0.1185]])
```

### CODE REVIEW

**Comment by mitkotak** [comment]
@TaufeqRazakh I am guessing you might just want `uuu` here.

**Comment by TaufeqRazakh** [comment]
Hi @mitkotak 

I am comparing computations in TensorSquarev2 and TensorSquare. I see in the initialization, we no longer define instructions, but instead, we use paths. 

However, the returned paths in `v2` are:
```
paths_uk = {dict: 3} {(0, 0, 0): Path(input_1_slice=Chunk(mul=1, dim=1, slice=slice(0, 1, None)), input_2_slice=None, output_slice=Chunk(mul=1, dim=1, slice=None)), (1, 1, 0): Path(input_1_slice=Chunk(mul=1, dim=3, slice=slice(1, 4, None)), input_2_slice=None, output_slice=Chu
paths_uvk = {dict: 1} {(0, 1, 1): Path(input_1_slice=Chunk(mul=1, dim=1, slice=slice(0, 1, None)), input_2_slice=Chunk(mul=1, dim=3, slice=slice(1, 4, None)), output_slice=Chunk(mul=1, dim=3, slice=None))}
paths_wk = {dict: 0} {}
```

and returned instructions in `legacy` are: 
```
instr = {list: 4} [(0, 0, 0, 'uuu', False, 0.3333333333333333), (0, 1, 2, 'uvuv', False, 3), (1, 1, 1, 'uuu', False, 0.2), (1, 1, 3, 'uuu', False, 2.5)]
```
Are they identical? Could this be the cause of the ordering error for `0e + 1e`

**Comment by mitkotak** [comment]
Can you do a compare with e3nn_jax.tensor_square since thats what I am basing my API on ?
Also isn't this module compiling with the jit flag turned off ?

**Comment by TaufeqRazakh** [comment]
Sounds good, will update soon

**Comment by TaufeqRazakh** [comment]
@mitkotak some help here to make these tests equivalent:

I have A test
```
@pytest.mark.parametrize("irreps_in", ["0e + 1e"])
def test_squaretp(irreps_in):
    x = o3.Irreps(irreps_in).randn(1, -1)
    square_tp_pt2 = torch.compile(o3.experimental.TensorSquarev2(irreps_in), fullgraph=True)
    square_tp = o3.TensorSquare(irreps_in)
    result_tp2 = square_tp_pt2(x)
    result_tp = square_tp(x)
    print(result_tp2)

```

How do I make this B test equivalent?
```
def test_tensor_square_simple():
    jax.config.update("jax_enable_x64", True)
    x = e3nn.IrrepsArray("1o", jnp.array([1.0, 0.0, 0.0]))
    print(x)
```

**Pull request closed without merging**
