### PR TITLE
Fix TorchScript warning "doesn't support instance-level annotations"

### PR DESCRIPTION
**Pull request by Linux-cpp-lisp**
## Description
In recent PyTorch versions, this warning has started coming up a lot:
```
UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
```

## How Has This Been Tested?
All unit tests pass locally, with GPU.

## Checklist:

- [ X ] I have read the [**CONTRIBUTING**](https://github.com/e3nn/e3nn/blob/main/.github/CONTRIBUTING.md) document.
- [ X ] My code follows the code style of this project.
- [ X ] I have updated the documentation (if relevant).
- [ X ] I have added tests that cover my changes (if relevant).
- [ X ] The modified code is cuda compatible (github tests don't test cuda) (if relevant).
- [ ] I have updated the [CHANGELOG](https://github.com/e3nn/e3nn/blob/main/.github/CHANGELOG.md).

### CODE REVIEW

**Comment by Linux-cpp-lisp** [comment]
See also https://github.com/pytorch/pytorch/issues/89064

**Comment by mariogeiger** [comment]
Tell me when you want to merge

**Comment by Linux-cpp-lisp** [comment]
Thanks @mariogeiger --- ideally just want to see the tests pass, and if anyone else wants to take a quick look to make sure I didn't make any typos / logical errors in this, since it touches some of the compilation logic that underpins most of the library.

**Comment by mitkotak** [comment]
Looks good from my side.

**Comment by mariogeiger** [comment]
There is a problem with the tests

**Comment by Linux-cpp-lisp** [comment]
Why does this file exist? https://github.com/e3nn/e3nn/blob/main/examples/conftest.py
It seems like a duplicate of the one in `tests/`...

**Comment by mariogeiger** [comment]
No idea, does it help it you delete it?

**Comment by Linux-cpp-lisp** [comment]
Let's find out 😄

**Comment by Linux-cpp-lisp** [comment]
I suspect it's due to a combination of that file and the fact that the GitHub actions are set up run any tests anywhere in the repo:
https://github.com/e3nn/e3nn/blob/main/.github/workflows/tests.yml#L56

instead of only in the `tests/` folder.  Is that intentional?

**Comment by mitkotak** [comment]
I remember the examples were failing because of torch-cluster, torch-sparse… import issues

**Comment by mitkotak** [comment]
For the Torch 2 test that is failing its running alright locally when I do, so not sure what's happening there
```
pytest --doctest-modules --ignore=docs/ tests/o3/experimental/test_fulltp.py
```

**Comment by Linux-cpp-lisp** [comment]
Is there a way to just not run tests or flake8 on anything in `experimental` right now?

**Comment by Linux-cpp-lisp** [comment]
Either way, it does look like all failures are unrelated to this PR, so I think we're good to merge, thanks!

**Comment by mitkotak** [comment]
Do you mind doing a `--ignore=tests/o3/experimental` ?

**Comment by mariogeiger** [comment]
Ok let me merge and feel free to make another PR to fix this test problem

**Comment by Linux-cpp-lisp** [comment]
Great, thanks guys!

**Pull request merged**
