### PR TITLE
Fx fixes

### PR DESCRIPTION
**Pull request by borisfom**
Changes to make TensorProduct classes FX-traceable

## Description

Those changes are partial and would only allow subset of classes used in DiffDock, pass FX symbolic_trace().
jit_script_fx needs to be set to False for this to work, too.

## Motivation and Context

Resolves: #???

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/e3nn/e3nn/blob/main/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [ ] The modified code is cuda compatible (github tests don't test cuda) (if relevant).
- [ ] I have updated the [Changelog](https://github.com/e3nn/e3nn/blob/main/ChangeLog.md).

### CODE REVIEW

**Comment by mariogeiger** [comment]
Thanks a lot for the PR, it looks good!
Is it ready to merge?

**Comment by borisfom** [comment]
> Thanks a lot for the PR, it looks good!
> Is it ready to merge?

Not sure, there is a test failure, but I can't tell if it's a problem or if it actually fixes earlier issue : 
FAILED tests/o3/tensor_product_test.py::test_input_weights_jit[float64] - Failed: DID NOT RAISE (<class 'RuntimeError'>, <class 'torch.jit.Error'>)

**Comment by mariogeiger** [comment]
I guess it's just because now some assertions are inside an if statement

**Comment by Linux-cpp-lisp** [comment]
Instead of wrapping things in conditionals, I think you could replace `assert` with `torch._assert(condition, message)` which is `fx` traceable.

**Comment by borisfom** [comment]
> I guess it's just because now some assertions are inside an if statement

Right; I have used Lisp's suggestion now :)

**Comment by borisfom** [comment]
@mariogeiger : I guess it's ready for merge now :)

**Comment by mariogeiger** [comment]
Good job

**Pull request merged**
