### PR TITLE
Remove CartesianTensor._rtp

### PR DESCRIPTION
**Pull request by mariogeiger**
```python
irreps = CartesianTensor("ij=-ji")

rtp = irreps.reduced_tensor_products()
# rtp is a nn.Module

irreps.from_cartesian(data, rtp=rtp)  # use rtp

irreps.from_cartesian(data)  # create a new ReducedTensorProducts at each call
```

### CODE REVIEW

**Comment by blondegeek** [comment]
Can the user still fix which rtp is used to convert the data? There are
users who need to do this because of the degeneracy of the change of basis
matrix and they may have existing matrices.

**Comment by mariogeiger** [comment]
"sill"? I don't think the user can do that right now.

I just made `ReducedTensorProducts` pickle-compatible using `CodeGenMixin`.
The user will be able to do that:

```python
irreps = CartesianTensor("ij=-ji")
torch.save(irreps.reduced_tensor_products(), "rtp")

# 6 month later...
irreps = CartesianTensor("ij=-ji")
rtp = torch.load("rtp")
irreps.from_cartesian(data, rtp=rtp)  # use rtp
```

**Comment by blondegeek** [comment]
Great! Thanks!

**Comment by mjwen** [comment]
Great solution, thanks!

**Pull request merged**
