### PR TITLE
Tetris with torch geometric Data and Batch and data_helpers.

### PR DESCRIPTION
**Pull request by blondegeek**

### CODE REVIEW

**Comment by mariogeiger** [comment]
I wait that we merge #87 before merging this one

**Comment by mariogeiger** [comment]
Do you have an idea why I get the following error:
`TypeError: forward() got an unexpected keyword argument 'size'` ?

**Comment by blondegeek** [comment]
Hmm... I did change `networks.py` to have `def forward(self, input, *args, **kwargs)` for `GatedConvNetwork`.

**Comment by blondegeek** [comment]
This happens when you run `python3 examples/point/tetris_torch_geo.py`? The code works for me.

**Comment by mariogeiger** [comment]
It works :-)

**Pull request merged**
