### PR TITLE
Codegen `fx.GraphModule`s with their own constants

### PR DESCRIPTION
**Pull request by Linux-cpp-lisp**
## Description
Switch `CodeGenMixin` from operating on `fx.Graph`s to `fx.GraphModule`s, which lets generated code carry around its own constants without having to pass them back and forth between the compiled `GraphModule` and its parent. (i.e. the w3js)

This also removes a lot of indexing and reshaping from `TensorProduct` — I don't know if it improves performance at all, but it does clean up the code.

## Motivation and Context
Decouple constants generated in codegen from the parent module, allowing eventual alternative codegen backends for `TensorProduct` without having to add or remove buffers on `TensorProduct`.

## How Has This Been Tested?
e3nn tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/e3nn/e3nn/blob/main/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [X] I have updated the documentation (if relevant).
- [X] I have added tests that cover my changes (if relevant).
- [X] All new and existing tests passed.
- [ ] I have updated the [Changelog](https://github.com/e3nn/e3nn/blob/main/ChangeLog.md).

### CODE REVIEW

**Comment by mariogeiger** [comment]
Why is it WIP?

**Comment by Linux-cpp-lisp** [comment]
I think because I thought it would get merged as part of sparse matmul or explicit backward, which require it — we can clean this and merge it now if you like?

**Comment by mariogeiger** [comment]
Yes! Tell me when I can merge

**Comment by Linux-cpp-lisp** [comment]
@mariogeiger let's see if the tests pass but this should be ready to merge, maybe double check it tho since it was a big merge updating it to `main` and I'm not familiar with what you've changed in recent weeks.

**Comment by Linux-cpp-lisp** [comment]
There's one other bug that I think got resolved in one of my other branches but that I have to find: these constatns aren't registered as buffers, so I think they fail to get moved to GPU

**Comment by Linux-cpp-lisp** [comment]
@mariogeiger should be good for review

**Pull request merged**
