### PR TITLE
cuda Tpnn

### PR DESCRIPTION
**Pull request by mariogeiger**

### CODE REVIEW

**Comment by blondegeek** [comment]
This commit is huge. Should we have a meeting to go through this one?

**Comment by mariogeiger** [comment]
@blondegeek This is not ready to be merged

**Comment by L-sky** [comment]
Tested locally with:
CudaToolkit 11.0
Pytorch 1.7.0
and matching pytorch_geometric dependencies

**Comment by L-sky** [comment]
It is up-to-date with master branch, but I'd suggest against merging it into master due to installation process. It would be better to make it a separate branch,

**Comment by L-sky** [comment]
It should be possible to build kernels / install from repo root with `pip install -e .`, provided there is working CudaToolkit,

**Comment by mariogeiger** [comment]
I close PR on master

**Pull request closed without merging**
